# Change baseurl before deploy
baseurl = "https://www.aestusguides.com"
languageCode = "en-us"
title = "Aestus Guides - Memoirs of a CRPG Sage"
description = "Deep dives into classic & modern computer RPGs, featuring advanced guides, system analysis, and tactical insights from a veteran of the Baldur's Gate series and beyond."

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5